[sources.messages_all]
type = "file"
include = [ "/Volumes/flowdata/messages/all.json" ]
data_dir="/Volumes/flowdata/messages"
read_from = "beginning"
max_line_bytes=99999999

[transforms.parse]
inputs = ["messages_all"]
type = "remap"
source = '''
  . = parse_json!(.message)
'''

[transforms.to_table]
type = "remap"
inputs = ["parse"]
source = '''
  d = {}
  d.Cid = .Cid
  d.Height = .Height
  d.Block = .BlockCid
  d.MessageRctExitCode = .MessageRct.ExitCode
  d.MessageRctReturn = .MessageRct.Return
  d.MessageRctGasUsed = .MessageRct.GasUsed

  if (.DecodedParams != null) {
    d.DecodedParams = .DecodedParams
  } else {
    d.DecodedParams = {}
  }

  d.SubCallOf = .SubCallOf
  d.From = .Addresses.From
  d.RobustFrom = .Addresses.RobustFrom
  d.RobustTo = .Addresses.RobustTo
  d.To = .Addresses.To
  d.Value = .Message.Value
  d.GasLimit = .Message.GasLimit
  d.GasFeeCap = .Message.GasFeeCap
  d.GasPremium = .Message.GasPremium
  d.Method = .Message.Method
  d.Params = .Message.Params
  . = d
'''


#[sinks.out]
#inputs = ["to_table"]
#type = "console"
#encoding.codec = "json"

[sinks.clickhouse]
type = "clickhouse"
inputs = [ "to_table" ]
database = "flow"
endpoint = "https://db.lotus-node.dev"
table = "messages"
compression = "gzip"
auth.strategy="basic"
auth.user="default"
auth.password="flow_p"
buffer.when_full="block"
buffer.type="disk"
buffer.max_size=9904900000000

[transforms.contracts]
type = "filter"
inputs = ["to_table"]
condition = '''.From == "t01" && .Method == 1 && .SubCallOf != null'''

[sinks.kafka_contract]
type = "kafka"
inputs = [ "contracts" ]
bootstrap_servers = "127.0.0.1:9092"
key_field = "Cid"
topic = "new_contract"
compression = "gzip"
buffer.when_full="block"
buffer.type="disk"
buffer.max_size=9904900000000

[sinks.kafka_contract.encoding]
codec = "json"