
[api]
enabled = true

[sources.in]
type = "stdin"

[transforms.parse]
inputs = ["in"]
type = "remap"
source = '''
  . = parse_json!(.message)
'''

[transforms.block]
type = "filter"
inputs = ["parse"]
condition = ".Block != null && .ActorId == null"

[transforms.message]
type = "filter"
inputs = ["parse"]
condition = ".Message != null"

[transforms.bls]
type = "filter"
inputs = ["parse"]
condition = ".ActorId != null"

[transforms.dedupe_bls]
type = "dedupe"
inputs = [ "bls" ]
cache.num_events=100000
fields.match=["ActorId", "Processed"]

[transforms.bench]
type = "filter"
inputs = ["parse"]
condition = '''.target_height != null'''

[sinks.out]
inputs = ["bench"]
type = "console"
encoding.codec = "json"

[transforms.to_table]
type = "remap"
inputs = ["message"]
source = '''
  d = {}
  d.Cid = .Cid
  d.Height = .Height
  d.Block = .BlockCid
  d.MessageRctExitCode = .MessageRct.ExitCode
  d.MessageRctReturn = .MessageRct.Return
  d.MessageRctGasUsed = .MessageRct.GasUsed
  d.SubCallOf = .SubCallOf
  d.From = .Addresses.From
  d.RobustFrom = .Addresses.RobustFrom
  d.RobustTo = .Addresses.RobustTo
  d.To = .Addresses.To
  d.Value = .Value
  d.GasLimit = .Message.GasLimit
  d.GasFeeCap = .Message.GasFeeCap
  d.GasPremium = .Message.GasPremium
  d.Method = .Message.Method
  d.Params =.Message.Params
  d.BlockTimestamp = .BlockTimestamp
  . = d
'''


[transforms.to_blk_table]
type = "remap"
inputs = ["block"]
source = '''
  d = {}
  d.Cid = .Cid
  d.Block = encode_json(.Block)
  d.Timestamp = .Block.Timestamp
  d.Height = .Block.Height
  . = d
'''

[sinks.clickhouse_bls]
type = "clickhouse"
inputs = [ "dedupe_bls" ]
database = "flow"
endpoint = "http://localhost:8123"
table = "actor_bls"
compression = "gzip"
auth.strategy="basic"
auth.user="flow_u"
auth.password="flow_p"
buffer.when_full="block"
buffer.type="disk"
buffer.max_size=500000000
batch.max_events=10

[sinks.clickhouse_blk]
type = "clickhouse"
inputs = [ "to_blk_table" ]
database = "flow"
endpoint = "http://localhost:8123"
table = "block"
compression = "gzip"
auth.strategy="basic"
auth.user="flow_u"
auth.password="flow_p"
buffer.when_full="block"
buffer.type="disk"
buffer.max_size=500000000
batch.max_events=10


[sinks.clickhouse_message]
type = "clickhouse"
inputs = [ "to_table" ]
database = "flow"
endpoint = "http://localhost:8123"
table = "messages"
compression = "gzip"
auth.strategy="basic"
auth.user="flow_u"
auth.password="flow_p"
buffer.when_full="block"
buffer.type="disk"
buffer.max_size=500000000
batch.max_events=10
