[sources.messages_all]
type = "file"
include = [ "/Volumes/flowdata/messages/all.json" ]
data_dir="/Volumes/flowdata/messages"
read_from = "beginning"
max_line_bytes=99999999

[sources.bls]
type = "file"
include = [ "/Volumes/flowdata/bls/all.json" ]
data_dir="/Volumes/flowdata/bls"
read_from = "beginning"
max_line_bytes=99999999

[transforms.parse]
inputs = ["messages_all"]
type = "remap"
source = '''
  . = parse_json!(.message)
'''

[transforms.parse_bls]
inputs = ["bls"]
type = "remap"
source = '''
  . = parse_json!(.message)
'''

[transforms.to_table]
type = "remap"
inputs = ["parse"]
source = '''
  d = {}
  d.Cid = .Cid
  d.Height = .Height
  d.Block = .BlockCid
  d.MessageRctExitCode = .MessageRct.ExitCode
  d.MessageRctReturn = .MessageRct.Return
  d.MessageRctGasUsed = .MessageRct.GasUsed
  d.SubCallOf = .SubCallOf
  d.From = .Addresses.From
  d.RobustFrom = .Addresses.RobustFrom
  d.RobustTo = .Addresses.RobustTo
  d.To = .Addresses.To
  d.Value = .Value
  d.GasLimit = .Message.GasLimit
  d.GasFeeCap = .Message.GasFeeCap
  d.GasPremium = .Message.GasPremium
  d.Method = .Message.Method
  d.Params =.Message.Params
  . = d
'''

[sinks.clickhouse_bls]
type = "clickhouse"
inputs = [ "parse_bls" ]
database = "flow"
endpoint = "http://localhost:8123"
table = "actor_bls"
compression = "gzip"
auth.strategy="basic"
auth.user="flow_u"
auth.password="flow_p"
buffer.when_full="block"
buffer.type="disk"
buffer.max_size=104900000000
batch.max_events=104900000000

[sinks.clickhouse_message]
type = "clickhouse"
inputs = [ "to_table" ]
database = "flow"
endpoint = "http://localhost:8123"
table = "messages"
compression = "gzip"
auth.strategy="basic"
auth.user="flow_u"
auth.password="flow_p"
buffer.when_full="block"
buffer.type="disk"
buffer.max_size=104900000000
batch.max_events=104900000000

[sinks.out]
inputs = ["bls"]
type = "console"
encoding.codec = "json"
