
[api]
enabled = true

[sources.in]
type = "stdin"

[transforms.parse]
inputs = ["in"]
type = "remap"
source = '''
  . = parse_json!(.message)
'''

[transforms.contract]
type = "filter"
inputs = ["parse"]
condition = '''.Message.From == "t01" || (.Message.To == "t01" && starts_with(to_string(.Message.From) ?? "", "t3")) || starts_with(to_string(.Message.From) ?? "", "t3")'''

[sinks.file_contract]
type = "file"
inputs = [ "contract" ]
compression = "none"
path = "./data/contract/contracts.json"
encoding.codec = "json"

